name: Build and Push Docker image

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build-and-push:
    uses: LeBogoo/workflows/.github/workflows/build-and-push.yml@v1.0.0
    with:
      image_name: "asteroids"
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}